spring:
  application:
    name: art-galery
  jackson:
    default-property-inclusion: non_null # avoid null in JSON response
    property-naming-strategy: SNAKE_CASE # set snake case format in JSON
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none # Use "validate" for production
    open-in-view: false
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET} # Secret is available in the docker-compose file

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enable: true
  info:
    title: Art Gallery API
    description: Tecnisis API
    version: 1.0.0
logging:
  level:
    org.springframework: DEBUG
    org.hibernate: DEBUG
    org.springframework.web: DEBUG
    org.springframework.http.converter.json: DEBUG

mapstruct:
  default:
    unmappedTargetPolicy: IGNORE # Avoid properties didn't mapped
